### ISSUE TITLE
Please consider change versioning/tagging convention

### ISSUE THREAD

**Issue by kloczek** [intel/eth-fast-fabric#6]
Corrently 5th part of the version is prefixed with dash. It would be goo to drop that part or replace dash by dot to make `eth-fast-fabric` easier to package as most of the package managemet software do mot accept dash as part of the version string.

**Comment by ToddRimmer** [comment]
> Corrently 5th part of the version is prefixed with dash. It would be goo to drop that part or replace dash by dot to make `eth-fast-fabric` easier to package as most of the package managemet software do mot accept dash as part of the version string.

Please clarify your request.  What distro is this comment with regard to?  On Rocky Linux 8.5 I did a quick check via "rpm -qa|grep [0-9]-[0-9]|wc -l and found 1616 rpms which had a dash in their version string.  Here is just one example:  perl-utils-5.26.3-420.el8.noarch   The convention is that the last part of a version string (build number) is preceded with a dash.  The actual versions reported by the rpm command are of the form: [name]-[version]-[release].[arch].rpm.  If I look at the the latest eth-tools-fastfabric-11.3.0.0-130.el8.x86_64  in the spec file Version is 11.3.0.0 and Release is 130%{?dist} and the dash shown is actually generated by the rpm command itself.   https://github.com/intel/eth-fast-fabric/blob/master/eth-tools.spec.in

**Comment by kloczek** [comment]
> Here is just one example: perl-utils-5.26.3-420.el8.noarch

Nope that "420" it is rpm package **release** whcih has nothing to do with source tree version.
https://src.fedoraproject.org/rpms/perl/blob/rawhide/f/perl.spec

**Comment by ToddRimmer** [comment]
In the rpm spec file Version is 11.3.0.0.  Is your concern simply the name of the git tags used in the repo:  https://github.com/intel/eth-fast-fabric/releases

**Comment by kloczek** [comment]
Issue is that that part ater dasz seems is random so it is hard to use that convention by auutomation.

**Comment by jijunwan** [comment]
changed versioning/tagging without build/release number. Feel free to reopen if it doesn't meet you request.

**Comment by kloczek** [comment]
Thank you very much 👍 😄
