### ISSUE TITLE
building failed on other os releases?

### ISSUE THREAD

**Issue by xiacunshun** [intel/eth-fast-fabric#7]
I am trying to build eth-fast-fabric on OpencloudOS (released by Tencent China), but got an error:
`/builddir/build/BUILD/eth-fast-fabric-11.3.0.0/OpenIb_Host/Makerules.project:174: *** BUILD_TARGET_OS_VERSION not defined.  Stop.`
It turns out that `funcs-ext.sh` cannot recognize the ID in /etc/os-release?
Is there any solution? e.g., adding other releases in `funcs-ext.sh`.

**Comment by acgoldma** [comment]
Hello, 

Presently, we do not support OpenCloudOS. 
If you would like to contribute a patch to add support we can include it in our package, however, we do not plan to validate on this OS at this time
If you wish to contribute a patch, feel free to use this previously accepted Pull Request as an example:  https://github.com/intel/eth-fast-fabric/pull/3

Additionally, it is possible to use a pre-built version of our IEFS Tool Suite. 
The OS check can be bypassed with `./INSTALL --force` or the RPMS can be installed manually.

**Comment by xiacunshun** [comment]
@acgoldma I have made a pull request to support OpenCloudOS.
thx.

**Comment by acgoldma** [comment]
@xiacunshun, your patch has been merged and will be included in a future release.
